### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_truncnorm'

### ISSUE THREAD

**Issue by Charlie0257** [namsan96/SiMPL#1]
When I run the `python simpl_meta_train.py  --help`, there is an error like the following:

`Traceback (most recent call last):
  File "simpl_meta_train.py", line 9, in <module>
    from simpl.alg.simpl import ContextPriorResidualNormalMLPPolicy, LowFixedGPUWorker, Simpl
  File "/home/charlie/PycharmProjects/SiMPL/simpl/alg/simpl/__init__.py", line 2, in <module>
    from .condition import *
  File "/home/charlie/PycharmProjects/SiMPL/simpl/alg/simpl/condition.py", line 6, in <module>
    from simpl.rl import StochasticNNPolicy
  File "/home/charlie/PycharmProjects/SiMPL/simpl/rl/__init__.py", line 1, in <module>
    from .policy import *
  File "/home/charlie/PycharmProjects/SiMPL/simpl/rl/policy/__init__.py", line 1, in <module>
    from .policy import *
  File "/home/charlie/PycharmProjects/SiMPL/simpl/rl/policy/policy.py", line 8, in <module>
    from torch_truncnorm import TruncatedNormal`
`ModuleNotFoundError: No module named 'torch_truncnorm'`

How to handle it?
Thanks

**Comment by namsan96** [comment]
Hi,

This was a missing requirement, please install the package from my fork:
`pip install git+https://github.com/namsan96/torch_truncnorm@main#torch_truncnorm`

Sorry for the mistake and thank you for reporting this.
I also found one more missing module, please pull once more to sync the latest commit (f5286924bd0502431b1f9904db631f6b1e13dce7)

**Comment by Charlie0257** [comment]
Thank you very much! The Error has been solved :)
